<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('chronicle_entries', function (Blueprint $table) {
            $table->id();
            
            // Core identification fields
            $table->string('type'); // 'auto' (generated by system) or 'manual' (entered by user)
            $table->string('category'); // e.g., 'history', 'leadership', 'wedding', 'funeral', 'custom'
            
            // Content
            $table->string('title');
            $table->text('description')->nullable();
            
            // Timeline mechanics
            $table->date('occurred_at'); // when it happened
            $table->date('ended_at')->nullable(); // when it ended (for periods/terms)
            
            // Polymorphic relation (who/what is this about?)
            // This allows linking an entry to a User, Member, Department, etc.
            $table->string('subject_type')->nullable();
            $table->unsignedBigInteger('subject_id')->nullable();
            
            // Additional flexible payload
            $table->json('meta_data')->nullable(); // store JSON blob (e.g. bride/groom names, old role, etc.)
            
            // Audit
            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            
            $table->timestamps();
            
            // Indexes for faster timeline queries
            $table->index('occurred_at');
            $table->index(['subject_type', 'subject_id']);
            $table->index('category');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('chronicle_entries');
    }
};
